<a href="https://colab.research.google.com/github/ombelote/Tensorflow-Practice/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Topics Covered:
+ Introduction to tensors
+ Getting information from tensors
+ Manipulating tensors
+ Tensors and Numpy
+ Using @tf. function (a way to speed up0 ur python functions)
+ Using GPUs with Tensorflow or TPU
+ Exercises


In [103]:
import tensorflow as tf
print(tf.__version__)

2.4.1


In [28]:
# Creating Ttensors with tf,constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [29]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [30]:
# Create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [31]:
  vector.ndim

1

In [32]:
matrix = tf.constant(([10,7],[7,10]))
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [33]:
matrix.ndim

2

In [34]:
# create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]],dtype= tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [35]:
another_matrix.ndim

2

In [36]:
# Lets create a tensor
tensor = tf.constant([
                      [[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]],
                      ])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [37]:
tensor.ndim

3

In [38]:
# Create the same tensor with tf.variable 
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [40]:
changable_tensor[0]=7

TypeError: ignored

In [41]:
changable_tensor[0].assign(7)
changable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [42]:
unchangable_tensor[0]=7

TypeError: ignored

In [ ]:
unchangable_tensor[0].assign(7)

# Creating Random Tensors
Random tensors are tensors of some arbritary size filled with random numbers


In [43]:
# Create 2 random but same tensors
random_1= tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1= random_1.normal(shape=(3,2))
random_2= tf.random.Generator.from_seed(42)
random_2= random_2.normal(shape=(3,2))

random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### shuffle the order of elements in a tensor


# we shuffle our data when we dont want the data to inherently learn the same value for a long time

In [44]:
not_shuffled= tf.constant([
                           [10,7],
                           [3,4],
                           [2,5]
                           ])
tf.random.set_seed(30)  # global level ramndom seed
tf.random.shuffle(not_shuffled,seed=42) # local level random seed
# we need to use both global and local level random seeds to produce the same kind of output
# the values should be different

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [45]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

#Other ways to create tensors

In [46]:
# Create a tensor of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [47]:
#Create a tensor of all zeroes
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

# Turn Numpy into Tensorflow
## The main differenc between tensorflow and numpy is that tensorflow can use gpus to run faster

In [48]:
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32)
numpy_A
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [49]:
A= tf.constant(numpy_A,shape=(2,3,4))
B= tf.constant(numpy_A)

A, B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

#Getting information from our tensors
When dealing with tensors we need to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [50]:
rank_4_tensor= tf.zeros([2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [51]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [52]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [53]:
# Get versions attributes of a Tensor
print('Datatype of every element: ',rank_4_tensor.dtype)
print('Number Of Dimensions: ', rank_4_tensor.ndim)
print('Shape of a Tensor: ',rank_4_tensor.shape)
print('Elements along first axis: ',rank_4_tensor.shape[0])
print('Elements along last axis: ',rank_4_tensor.shape[-1])
print('total number of elements in our tensor: ',tf.size(rank_4_tensor))
print('total number of elements in our tensor: ',tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number Of Dimensions:  4
Shape of a Tensor:  (2, 3, 4, 5)
Elements along first axis:  2
Elements along last axis:  5
total number of elements in our tensor:  tf.Tensor(120, shape=(), dtype=int32)
total number of elements in our tensor:  120


# Indexing Tensors


In [54]:
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [55]:
rank_4_tensor.shape

TensorShape([2, 3, 4, 5])

In [56]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [57]:
rank_2_tensor= tf.constant([
                            [10,7],
                            [3,4]                             
])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [58]:
# Adding an extra dimension to our rank 2 tensor
rank_3_tensor= rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [59]:
# Using tf. expand_dims
tf.expand_dims(rank_2_tensor,axis=-1) #'-1' means the final axis


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [60]:
tf.expand_dims(rank_2_tensor,axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

# Manipulating Tensors

##Basic Operations
`+`,`-`,`*`,`/`

In [61]:
tensor = tf.constant([
                      [10,7],
                      [3,4]
                      ])
tensor +10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [62]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [63]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [64]:
tensor-10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [65]:
# Using the inbuilt tensorflow functions (THey are faster)
# tf.math.multiply
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [66]:
tf.add(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

# Matrix Multiplication (Dot Product)

In [67]:
# tf.linalg.matmul
print(tensor)
# Dot Product
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [68]:
# Element wise
tensor*tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [69]:
# dot product
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [70]:
X= tf.constant([
                [1,2],
                [3,4],
                [5,6]
])
Y= tf.constant([
                [7,8],
                [9,10],
                [11,12]
])

In [71]:
X*Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7, 16],
       [27, 40],
       [55, 72]], dtype=int32)>

In [100]:
X @ Y

InvalidArgumentError: ignored

In [101]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [102]:
# Lets change the shape of Y
tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [73]:
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [74]:
X @ tf.transpose(Y)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

**The Dot Product**
* `tf.matmul()`
* `tf.tensordot()`

In [75]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [76]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [77]:
tf.tensordot(X, tf.reshape(Y,shape=(2,3)), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [78]:
#Check the values of Y, reshape Y and transposed Y
print('Normal Y: ')
print(Y,'\n')

print('Y with reshape: ')
print(tf.reshape(Y, shape=(2,3)),'\n')

print('Transposed Y: ')
print(tf.transpose(Y),'\n')

Normal Y: 
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y with reshape: 
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Transposed Y: 
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32) 



Generally we transpose rather than reshape

# Change the datatype of a tensor

In [79]:
B= tf.constant([1.4,7.4])
B.dtype

tf.float32

In [80]:
C= tf.constant([7,10])
C.dtype

tf.int32

In [81]:
D = tf.cast(B, dtype=tf.float16)
D.dtype

tf.float16

In [82]:
E = tf.cast(C, dtype=tf.float16) 
E.dtype

tf.float16

### Aggregating tensors
Aggregating tensore = condencing them from multiple values down to a samller amount of values.

In [83]:
D= tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [84]:
#Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets get through the following forms of aggregations
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [85]:
import numpy as np

In [86]:
E= tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([69, 77, 65,  0, 41, 69, 21, 96, 58, 36, 81, 92, 80, 71, 88, 93,  1,
       93,  6, 10, 65, 65, 78, 88, 91, 93, 42,  3, 75, 86, 40,  8, 20,  4,
       85, 79, 82, 13, 98, 37, 44, 83,  5, 65, 35, 55, 96, 98, 21, 31])>

In [87]:
tf.size(E).numpy(), E.shape , E.ndim

(50, TensorShape([50]), 1)

In [88]:
#find the minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [89]:
#find the max
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [90]:
#find the mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=56>

In [91]:
#find the sum
tf.reduce_sum(E)


<tf.Tensor: shape=(), dtype=int64, numpy=2832>

In [108]:
# find variance 
tf.math.reduce_variance(tf.cast(E, tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=1037.5103>

In [110]:
tf.math.std_dev(tf.cast(E, tf.float32))

AttributeError: ignored

In [96]:
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=1037>

In [97]:
# std_dev
tfp.stats.stddev(tf.cast(E, dtype= tf.float32))
# we need float32 to calculate std_dev

<tf.Tensor: shape=(), dtype=float32, numpy=32.210407>

#Find the positional maximum and minimum

In [111]:
# Create a new tensor for finding positional minimum and maximum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [112]:
# FInd the positional max
tf.argmax(F) 

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [113]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [114]:
# FInd the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [115]:
# CHeck for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)

In [116]:
#Find te positional min
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [117]:
# Find the min using pos min index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [119]:
#Create a tensor to get started
tf.random.set_seed(42)
G= tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 50), dtype=float32, numpy=
array([[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
          0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
          0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
          0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
          0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
          0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
          0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
          0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
          0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
          0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]],
      dtype=float32)>

In [120]:
G.shape

TensorShape([1, 1, 1, 50])

In [121]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensors

In [124]:
some_list= [0,1,2,3,4]
tf.one_hot(some_list, depth= 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [125]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=5, on_value='Used',off_value= "NotUsed")

<tf.Tensor: shape=(5, 5), dtype=string, numpy=
array([[b'Used', b'NotUsed', b'NotUsed', b'NotUsed', b'NotUsed'],
       [b'NotUsed', b'Used', b'NotUsed', b'NotUsed', b'NotUsed'],
       [b'NotUsed', b'NotUsed', b'Used', b'NotUsed', b'NotUsed'],
       [b'NotUsed', b'NotUsed', b'NotUsed', b'Used', b'NotUsed'],
       [b'NotUsed', b'NotUsed', b'NotUsed', b'NotUsed', b'Used']],
      dtype=object)>

### Squaring, log, square root

In [127]:
# Create a new tensor
H= tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [128]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [130]:
tf.sqrt(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
       2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>

In [133]:
#find the log
tf.math.log(tf.cast(H, dtype= tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and Numpy

Tensorflow interacts directly with Numpy

Numpy can be useful to access the elements directly

In [134]:
J= tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [135]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [136]:
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [137]:
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

See how the dtypes are different

In [140]:
J[[0]]

<tf.Tensor: shape=(), dtype=float64, numpy=3.0>

In [141]:
J.numpy()[0]

3.0